/**
 * dtls_wolfssl_session.cpp — DtlsSession via wolfSSL DTLS 1.2
 *
 * Uses custom I/O callbacks to bridge wolfSSL's non-blocking mode
 * with NimRTC's feed_inbound/take_outbound memory-buffer model.
 *
 *   feed_inbound(bytes) → recv_buf_ → wolfSSL I/O recv callback
 *   wolfSSL I/O send callback → send_buf_ → take_outbound() returns queue
 *
 * Handshake is driven by repeated wolfSSL_accept()/connect() calls,
 * returning WANT_READ/WANT_WRITE when more input is needed or more
 * output is ready.
 */

#ifdef _WIN32
#define _WIN32_WINNT 0x0601
#endif

#include "nimrtc/dtls/dtls_wolfssl_session.hpp"

#include <nimrtc/core/log.hpp>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <chrono>
#include <fstream>
#include <mutex>
#include <functional>
#ifndef _WIN32
#include <arpa/inet.h>
#endif

// wolfSSL headers use anonymous structs (a GNU extension); suppress
// -Wpedantic for these third-party headers.  Must push BEFORE the first
// wolfSSL include because ssl.h transitively pulls in random.h which
// contains the offending anonymous struct.
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
#endif

#include <wolfssl/options.h>
#include <wolfssl/ssl.h>
// internal.h is needed for `ssl->arrays->masterSecret` / `ssl->arrays->
// clientRandom`, which wolfSSL deliberately does NOT expose via the
// public API.  The public `wolfSSL_get_client_random()` returns the
// client random (good), but there is NO public getter for
// master_secret — the only observer-side hook that wolfSSL offers is
// `wolfSSL_CTX_set_keylog_callback()`, and in wolfSSL 6.x that hook
// is invoked ONLY from SendClientKeyExchange (client side).  In a DTLS
// server, the master secret is derived inside DoClientKeyExchange
// and the callback never fires — so server-side keylog files stay
// 0 bytes for that reason alone.  Reading directly from `Arrays`
// (after the handshake returns WOLFSSL_SUCCESS) is what BoringSSL's
// debug builds do too, and is safe because at that point the
// handshake has already authenticated the peer.
#include <wolfssl/internal.h>
#include <wolfssl/wolfcrypt/settings.h>
#include <wolfssl/wolfcrypt/error-crypt.h>
#include <wolfssl/wolfcrypt/sha256.h>
#include <wolfssl/wolfcrypt/asn.h>
#include <wolfssl/wolfcrypt/random.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#endif

// Undo the 'New' macro that <windows.h> defines (if present; no-op otherwise).
#ifdef New
#undef New
#endif

// Cross-platform fopen — MSVC provides fopen_s; on Linux/Unix use fopen.
#ifndef _WIN32
inline int fopen_s(FILE** fp, const char* path, const char* mode) {
    *fp = std::fopen(path, mode);
    return (*fp != nullptr) ? 0 : -1;
}
#endif

namespace {

using nimrtc::dtls::Config;
using nimrtc::dtls::DtlsRole;
using nimrtc::dtls::SrtpProfile;

// ---------------------------------------------------------------------------
// Resolution for the bundled ECC cert + key
//
// The cert at `tests/wolfssl_dtls/certs/server-ecc.pem` is generated by
// `scripts/build_dtls_cert.py` (see comment there) so it carries a
// `subjectAltName` extension — Chrome (BoringSSL) refuses to complete
// a DTLS handshake against a CA:FALSE cert that lacks SAN, sending
// fatal alert 46 ("certificate_unknown").
//
// Lookup order is "build dir, then source tree" so the test harness can
// drop an alternative cert into `build/tests/<cfg>/certs/` and have it
// win without recompiling.
// ---------------------------------------------------------------------------
std::string get_wolfssl_cert_path() {
    const char* candidates[] = {
        // Build-output copies seeded by CMake's copy_if_different rule
        // (see tests/wolfssl_dtls/CMakeLists.txt and friends).
        "certs/server-ecc.pem",
        // Source-tree fixtures.
        "tests/wolfssl_dtls/certs/server-ecc.pem",
        "src/third_party/wolfssl/src/certs/server-ecc.pem",
        "../../src/third_party/wolfssl/src/certs/server-ecc.pem",
        "../src/third_party/wolfssl/src/certs/server-ecc.pem",
    };
    for (auto p : candidates) {
        FILE* f = nullptr;
        if (fopen_s(&f, p, "rb") == 0 && f) {
            fclose(f);
            return std::string(p);
        }
    }
    return "certs/server-ecc.pem";
}

std::string get_wolfssl_key_path() {
    const char* candidates[] = {
        "certs/ecc-key.pem",
        "tests/wolfssl_dtls/certs/ecc-key.pem",
        "src/third_party/wolfssl/src/certs/ecc-key.pem",
        "../../src/third_party/wolfssl/src/certs/ecc-key.pem",
        "../src/third_party/wolfssl/src/certs/ecc-key.pem",
    };
    for (auto p : candidates) {
        FILE* f = nullptr;
        if (fopen_s(&f, p, "rb") == 0 && f) {
            fclose(f);
            return std::string(p);
        }
    }
    return "certs/ecc-key.pem";
}

std::string hex_colon(const std::uint8_t* data, std::size_t len) {
    std::string s;
    s.reserve(len * 3);
    for (std::size_t i = 0; i < len; ++i) {
        char buf[3];
        std::snprintf(buf, sizeof(buf), "%02X", data[i]);
        s += buf;
        if (i + 1 < len) s += ':';
    }
    return s;
}

[[maybe_unused]]
std::string fingerprint_sha256_from_der(const std::uint8_t* der,
                                        std::size_t der_len) {
    std::uint8_t hash[32];
    wc_Sha256 sha;
    wc_InitSha256(&sha);
    wc_Sha256Update(&sha, der, static_cast<word32>(der_len));
    wc_Sha256Final(&sha, hash);
    return hex_colon(hash, 32);
}

// SHA-256 over a buffer, lowercase hex.
static std::string sha256_hex(const std::uint8_t* data, std::size_t len) {
    std::uint8_t hash[32];
    wc_Sha256 sha;
    wc_InitSha256(&sha);
    wc_Sha256Update(&sha, data, static_cast<word32>(len));
    wc_Sha256Final(&sha, hash);
    std::string s;
    s.reserve(32 * 2);
    static const char* tab = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        s.push_back(tab[hash[i] >> 4]);
        s.push_back(tab[hash[i] & 0xF]);
    }
    return s;
}

// Compute SHA-256 over the DER-encoded X.509 certificate as a whole.
//
// RFC 8122 (and draft-ietf-mmusic-rfc4572-update which it obsoletes)
// defines the SDP `a=fingerprint` attribute as the SHA-256 hash of the
// ENTIRE DER-encoded certificate (including its signature), NOT the
// SubjectPublicKeyInfo (SPKI) — that was the "raw public key" path
// described in RFC 7250, which WebRTC does not follow.  Chrome's
// BoringSSL verifier and the WebRTC spec both hash the DER cert bytes
// verbatim; mismatching the SDP `a=fingerprint` value against the
// cert's DER SHA-256 (instead of its SPKI SHA-256) is what triggers
// fatal alert 46 ("certificate_unknown") during Chrome interop.
static std::string cert_sha256_hex(const std::uint8_t* cert_der,
                                    std::size_t cert_der_len) {
    return sha256_hex(cert_der, cert_der_len);
}

// Dummy verify callback — returns 1 (success) for every peer cert.
// We use WOLFSSL_VERIFY_PEER (not VERIFY_NONE) so that wolfSSL decodes
// the peer certificate and populates ssl->peerCert, which our
// verify_peer_spki() below reads to compute the SDP fingerprint hash.
// Without this callback accepting self-signed certs the handshake would
// abort with ASN_NO_SIGNER_E before KEEP_PEER_CERT's
// `CopyDecodedToX509(&ssl->peerCert, …)` block ever runs.
static int dummy_verify_callback(int /*preverify*/, WOLFSSL_X509_STORE_CTX* /*store*/) {
    return 1;
}

#if defined(HAVE_SECRET_CALLBACK)
// Native NSS keylog callback wired into wolfSSL via
// wolfSSL_CTX_set_keylog_callback().  Called once per handshake with a
// fully-formed NSS-format line ("CLIENT_RANDOM <hex> <hex>\n" — note
// trailing newline).  We just append to the file path held by the
// NIMRTC_DTLS_KEYLOG env var (looked up once at registration time
// and cached).  The append is mutex-guarded so concurrent sessions in
// the same process don't interleave bytes.
static void keylog_to_file(const WOLFSSL* /*ssl*/, const char* line) {
    static std::mutex mu;
    static const char* path = []() -> const char* {
        const char* p = std::getenv("NIMRTC_DTLS_KEYLOG");
        return (p && *p) ? p : nullptr;
    }();
    if (!path || !line) return;
    std::lock_guard<std::mutex> g(mu);
    std::ofstream k(path, std::ios::app);
    if (!k.is_open()) return;
    k << line;
    if (line[0] && line[std::strlen(line) - 1] != '\n') k << '\n';
    k.flush();
}
#endif

static const char* srtp_profile_name(SrtpProfile p) {
    // wolfSSL accepts a colon-separated list of profile names; the names
    // are the IANA "DTLS-SRTP protection profiles" (RFC 5764 §4.1.2).
    // IMPORTANT: wolfSSL's profile literal is `SRTP_AES128_GCM` WITHOUT
    // the `_80` suffix — the suffix denotes SRTP auth tag length and is
    // not part of the use_srtp extension string.  Using `SRTP_AES128_GCM_80`
    // silently no-ops in wolfSSL and `wolfSSL_export_dtls_srtp_keying_material`
    // then returns 0 bytes.
    switch (p) {
        case SrtpProfile::Aes128CmSha1_80: return "SRTP_AES128_CM_SHA1_80";
        case SrtpProfile::Aes128CmSha1_32: return "SRTP_AES128_CM_SHA1_32";
        case SrtpProfile::Aes128Gcm:        return "SRTP_AES128_GCM";
        case SrtpProfile::Aes256CmSha1_80: return "SRTP_AES256_CM_SHA1_80";
        default:                            return "SRTP_AES128_CM_SHA1_80";
    }
}

}  // namespace

// ---------------------------------------------------------------------------
// NIMRTC_DTLS_TRACE / NIMRTC_DTLS_KEYLOG / NIMRTC_DTLS_DUMP
// ---------------------------------------------------------------------------
// Three env vars that the e2e harness (tools/run_e2e_acceptance.py) sets
// before spawning demo-p2p.  Earlier the harness set them but no C++ code
// ever read them, so trace/keylog stayed at 0 bytes — the very failure
// we're now fixing.  All three are lazy-initialised from getenv() once
// per process and cached in a function-local static, so the per-record
// hot path stays branch-free.
//
//   NIMRTC_DTLS_TRACE=<path>   — append-only handshake event log
//                                (open / send / recv / complete / failed)
//   NIMRTC_DTLS_KEYLOG=<path>  — NSS-format keylog:
//        CLIENT_RANDOM <client_random_hex> <master_secret_hex>
//   NIMRTC_DTLS_DUMP=1         — hex-dump every record that passes
//                                through io_send / io_recv
//
namespace nimrtc::dtls::diag {

inline std::mutex& trace_mu() { static std::mutex m; return m; }

inline const char* trace_path()  { static const char* p = std::getenv("NIMRTC_DTLS_TRACE");  return p; }
inline const char* keylog_path() { static const char* p = std::getenv("NIMRTC_DTLS_KEYLOG"); return p; }
inline bool        dump_enabled(){ static const bool b = []{
    const char* v = std::getenv("NIMRTC_DTLS_DUMP"); return v && v[0] && v[0] != '0';
}(); return b; }

inline std::ofstream& trace_stream() {
    static std::ofstream s{trace_path() ? trace_path() : "",
                           std::ios::app};
    return s;
}

inline void trace(const std::string& msg) {
    if (!trace_path()) return;
    std::lock_guard<std::mutex> g(trace_mu());
    auto& s = trace_stream();
    if (!s.is_open()) return;
    s << msg << '\n';
    s.flush();
}

inline void hex_dump_record(const char* dir, const void* buf, std::size_t n) {
    if (!dump_enabled()) return;
    if (n < 13) return;     // not a full DTLS record header
    const auto* p = static_cast<const std::uint8_t*>(buf);
    // content_type | version | epoch | sequence_number | length | data…
    std::uint16_t ver    = (std::uint16_t(p[1]) << 8) | p[2];
    std::uint16_t epoch  = (std::uint16_t(p[3]) << 8) | p[4];
    std::uint64_t seq    = 0;
    for (int i = 0; i < 6; ++i) seq = (seq << 8) | p[5 + i];
    std::uint16_t len    = (std::uint16_t(p[11]) << 8) | p[12];
    const char* ct_name  = "?";
    switch (p[0]) {
        case 20: ct_name = "ChangeCipherSpec"; break;
        case 21: ct_name = "Alert";            break;
        case 22: ct_name = "Handshake";        break;
        case 23: ct_name = "AppData";          break;
        default:  break;
    }
    char hdr[200];
    std::snprintf(hdr, sizeof(hdr),
        "%s DTLS ct=%u(%s) ver=0x%04x epoch=%u seq=%llu len=%u",
        dir, p[0], ct_name, ver, epoch,
        (unsigned long long)seq, len);

    // Full payload hex-dump (up to 256 bytes to avoid runaway output).
    std::string body;
    if (n > 13 && len > 0) {
        std::size_t show = std::min<std::size_t>(256, n - 13);
        body.reserve(show * 3 + 4);
        for (std::size_t i = 0; i < show; ++i) {
            char b[4];
            std::snprintf(b, sizeof(b), "%02x", p[13 + i]);
            body += b;
            if (i + 1 < show) body += ' ';
        }
        if (show < n - 13) body += " ...";
    }
    trace(std::string(hdr) + (body.empty() ? "" : " body=" + body));
    // If this record is followed by more data in the buffer, recurse to dump the next record.
    std::size_t this_record_len = 13 + len;
    if (this_record_len < n) {
        hex_dump_record(dir, p + this_record_len, n - this_record_len);
    }
}

inline void write_keylog_line(const std::uint8_t client_random[32],
                              const std::uint8_t master_secret[48]) {
    if (!keylog_path()) return;
    std::lock_guard<std::mutex> g(trace_mu());
    std::ofstream k(keylog_path(), std::ios::app);
    if (!k.is_open()) return;
    auto hex = [](const std::uint8_t* p, std::size_t n) {
        std::string s; s.reserve(n * 2);
        for (std::size_t i = 0; i < n; ++i) {
            char b[3]; std::snprintf(b, sizeof(b), "%02x", p[i]); s += b;
        }
        return s;
    };
    k << "CLIENT_RANDOM " << hex(client_random, 32) << ' '
      << hex(master_secret, 48) << '\n';
}

}  // namespace nimrtc::dtls::diag

namespace nimrtc::dtls {

// ---------------------------------------------------------------------------
// DtlsSessionWolfSSL::Impl
// ---------------------------------------------------------------------------

struct DtlsSessionWolfSSL::Impl {
    Config        config;
    nimrtc::dtls::DtlsState state = nimrtc::dtls::DtlsState::Closed;
    bool          open_called = false;
    /** Reentrancy guard for pump_handshake() — see pump_handshake(). */
    bool          pumping_   = false;

    WOLFSSL_CTX*  ctx = nullptr;
    WOLFSSL*      ssl = nullptr;

    std::vector<std::uint8_t> recv_buf_;
    std::vector<std::uint8_t> send_buf_;
    std::vector<nimrtc::dtls::DtlsRecord> outbound_;

    SOCKADDR_IN   peer_addr{};
    bool          peer_set  = false;
    std::string   peer_host;
    std::uint16_t peer_port = 0;

    nimrtc::dtls::Fingerprint  local_fp_;
    /** Expected peer SPKI SHA-256 (raw bytes).  Empty = no pin set yet —
     *  verify_peer_spki() will log a warning and accept the handshake
     *  fail-open.  Set via set_peer_fingerprint(). */
    std::vector<std::uint8_t>  expected_peer_fp_;
    /** True if the application has called set_peer_fingerprint() with a
     *  32-byte SHA-256 value.  Used by verify_peer_spki() to distinguish
     *  "pin is empty because no pin was set" (allow) from "pin is empty
     *  because the application forgot to set it" (also allow, with a
     *  warning). */
    bool expected_peer_fp_set_ = false;
    std::optional<nimrtc::dtls::SrtpKeyingMaterial> srtp_keys_;

    Stats         stats_instance{};
    std::chrono::steady_clock::time_point handshake_start_{};

    ~Impl() { teardown(); }

    // -- wolfSSL I/O callbacks ----------------------------------------------

    static int io_recv(WOLFSSL* ssl, char* buf, int len, void* /*ctx*/) {
        auto* self = reinterpret_cast<DtlsSessionWolfSSL::Impl*>(
            wolfSSL_GetIOReadCtx(ssl));
        if (!self || self->recv_buf_.empty()) {
            // WANT_READ — non-blocking. wolfSSL will retry when more bytes
            // arrive via feed_inbound().
            return WOLFSSL_CBIO_ERR_WANT_READ;
        }
        int n = static_cast<int>(std::min<std::size_t>(
            self->recv_buf_.size(), static_cast<std::size_t>(len)));
        std::memcpy(buf, self->recv_buf_.data(), static_cast<std::size_t>(n));
        self->recv_buf_.erase(self->recv_buf_.begin(),
                              self->recv_buf_.begin() + n);
        nimrtc::dtls::diag::hex_dump_record("RECV", buf,
                                            static_cast<std::size_t>(n));
        return n;
    }

    static int io_send(WOLFSSL* ssl, char* buf, int len, void* /*ctx*/) {
        auto* self = reinterpret_cast<DtlsSessionWolfSSL::Impl*>(
            wolfSSL_GetIOWriteCtx(ssl));
        if (!self) return -1;
        auto old = self->send_buf_.size();
        self->send_buf_.resize(old + static_cast<std::size_t>(len));
        std::memcpy(self->send_buf_.data() + old, buf,
                    static_cast<std::size_t>(len));
        nimrtc::dtls::diag::hex_dump_record("SEND", buf,
                                            static_cast<std::size_t>(len));
        return len;
    }

    // -- Setup --------------------------------------------------------------

    bool setup_context() {
        if (config.role == DtlsRole::Server) {
            ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method());
        } else {
            ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method());
        }
        if (!ctx) {
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: failed to create CTX");
            return false;
        }

        // RFC 5764 §5 — DTLS-SRTP cipher suites are restricted to two GCM
        // suites.  ECDHE-ECDSA-AES128-SHA256 (a CBC-HMAC suite) is NOT in
        // the RFC 5764 list and Chrome will silently drop the handshake if
        // we offer it as the only alternative.  AES256-GCM-SHA384 is
        // preferred by some Chrome versions (notably Android/enterprise
        // builds) and must be present or those clients fall back to a
        // weaker suite or fail outright.
        //
        // wolfSSL cipher names use OpenSSL conventions; the mapping to
        // IANA cipher suite IDs:
        //   ECDHE-ECDSA-AES128-GCM-SHA256 → TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xC02B)
        //   ECDHE-ECDSA-AES256-GCM-SHA384 → TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xC02C)
        int rc = wolfSSL_CTX_set_cipher_list(
            ctx, "ECDHE-ECDSA-AES128-GCM-SHA256:"
                 "ECDHE-ECDSA-AES256-GCM-SHA384");
        if (rc != WOLFSSL_SUCCESS) {
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: failed to set cipher list");
            return false;
        }

        // Extended Master Secret (RFC 7627) — REQUIRED for DTLS-SRTP per
        // RFC 5764 §5 ("the use of the Extended Master Secret extension
        // is REQUIRED").  Chrome enforces EMS since M76.
        //
        // Implementation: we deliberately do NOT add a compile-time or
        // runtime check here.  An `#ifndef HAVE_EXTENDED_MASTER` block
        // triggers MSVC warning C4702 (unreachable code) once the macro
        // is defined, and a `static_assert(HAVE_EXTENDED_MASTER == 1, ...)`
        // is a syntax error because the macro expands to nothing.
        //
        // Instead, the EMS requirement is enforced at the *configuration*
        // level via src/third_party/wolfssl/CMakeLists.txt, which sets
        // `WOLFSSL_EXTENDED_MASTER_SECRET=ON`.  This causes wolfSSL's
        // options.h to define `HAVE_EXTENDED_MASTER`, which wolfSSL's
        // internal.c reads at InitSSL_Ctx() time to set ctx->haveEMS = 1.
        // Every NimRTC DTLS handshake therefore negotiates EMS by default.
        //
        // If a downstream user turns off EMS in their wolfSSL build (via
        // WOLFSSL_EXTENDED_MASTER_SECRET=OFF), the handshake will silently
        // negotiate without EMS and Chrome will reject it with
        // "extended_master_secret_required".  We accept that as a build
        // configuration error, not a NimRTC bug.


        const std::string cert_path = get_wolfssl_cert_path();
        const std::string key_path  = get_wolfssl_key_path();

        rc = wolfSSL_CTX_use_certificate_file(ctx, cert_path.c_str(),
                                              WOLFSSL_FILETYPE_PEM);
        if (rc != WOLFSSL_SUCCESS) {
            nimrtc::core::log::Logger::instance().error(
                std::string("wolfSSL: failed to load cert from ") + cert_path);
            return false;
        }

        rc = wolfSSL_CTX_use_PrivateKey_file(ctx, key_path.c_str(),
                                               WOLFSSL_FILETYPE_PEM);
        if (rc != WOLFSSL_SUCCESS) {
            nimrtc::core::log::Logger::instance().error(
                std::string("wolfSSL: failed to load key from ") + key_path);
            return false;
        }

        if (!wolfSSL_CTX_check_private_key(ctx)) {
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: private key does not match certificate");
            return false;
        }

        compute_local_fingerprint();

        // Dump cert details right after load — invaluable when Chrome
        // rejects with alert 46 (CU).  Pull the cert from disk (we have the
        // path) and emit its fingerprint to match what we publish in SDP,
        // so an external verifier can confirm the wire and the SDP agree.
        //
        // wolfSSL version compatibility: the legacy OpenSSL-compat
        // helpers (wolfSSL_CTX_get_certificate / _get_subject_oneline /
        // _X509_get_ext_oid / _X509_ext_is_critical) were removed in
        // newer wolfSSL.  wolfSSL_CTX_get0_certificate exists only
        // behind OPENSSL_EXTRA + KEEP_OUR_CERT which we don't enable
        // (we use wolfSSL as a DTLS-only backend, not an HTTPS stack).
        // Skip the in-memory X509 dump entirely — `compute_local_fingerprint()`
        // already logs the SHA-256 we pin against, which is what matters
        // when chasing Chrome SDP/pinning mismatches.
        (void)ctx;  // silence unused-parameter warning

        std::string srtp_profiles = srtp_profile_name(config.srtp_profile);
        rc = wolfSSL_CTX_set_tlsext_use_srtp(ctx, srtp_profiles.c_str());
        // wolfSSL returns 0 on success (OpenSSL convention), 1 on error.
        if (rc != 0) {
            nimrtc::core::log::Logger::instance().warn(
                std::string("wolfSSL: SRTP profile not set (rc=") +
                std::to_string(rc) + ")");
        } else {
            nimrtc::core::log::Logger::instance().info(
                std::string("wolfSSL: SRTP profile set: ") + srtp_profiles);
        }

        // WebRTC-mandated self-signed cert flow: we cannot rely on
        // WOLFSSL_VERIFY_NONE because wolfSSL won't even decode the peer
        // cert in that mode (peerCert stays empty, the
        // KEEP_PEER_CERT-gated wolfSSL_get_peer_certificate() returns
        // NULL, and the SPKI pin in verify_peer_spki() below has nothing
        // to compare against).  Instead we use WOLFSSL_VERIFY_PEER +
        // a verify callback that always succeeds — wolfSSL walks the
        // cert chain and populates peerCert, then asks our callback
        // whether to accept, and we say yes regardless of chain
        // validity.  The actual MITM check happens in
        // verify_peer_spki() via the SDP `a=fingerprint` hash.
        //
        // See src/modules/dtls/src/dtls_wolfssl_session.cpp
        // `verify_peer_spki()` for the post-handshake pin check.
        wolfSSL_CTX_set_verify(ctx,
                               WOLFSSL_VERIFY_PEER |
                                   WOLFSSL_VERIFY_FAIL_IF_NO_PEER_CERT,
                               &dummy_verify_callback);

        // Native NSS-format keylog callback (only available when
        // wolfSSL was built with HAVE_SECRET_CALLBACK).  When the env
        // var NIMRTC_DTLS_KEYLOG is set, wolfSSL itself writes lines
        // like `CLIENT_RANDOM <hex> <hex>` to the file as soon as the
        // master secret is derived — same format Wireshark expects,
        // same format Chrome's BoringSSL emits via --ssl-key-log-file.
        //
        // This is the ONLY way to get master_secret without a private
        // wolfSSL API (master_secret lives in ssl->arrays and there's
        // no public getter).  Tying it to the env var means production
        // builds (env var unset) pay zero overhead.
#if defined(HAVE_SECRET_CALLBACK)
        if (nimrtc::dtls::diag::keylog_path()) {
            wolfSSL_CTX_set_keylog_callback(ctx, &keylog_to_file);
        }
#endif
        return true;
    }

    void compute_local_fingerprint() {
        const std::string cert_path = get_wolfssl_cert_path();

        FILE* f = nullptr;
        if (fopen_s(&f, cert_path.c_str(), "rb") != 0 || !f) return;

        // Slurp entire file.
        fseek(f, 0, SEEK_END);
        long sz = ftell(f);
        fseek(f, 0, SEEK_SET);
        if (sz <= 0) { fclose(f); return; }

        std::vector<unsigned char> pem(static_cast<std::size_t>(sz) + 1);
        size_t n = fread(pem.data(), 1, static_cast<std::size_t>(sz), f);
        pem[n] = 0;
        fclose(f);

        // Convert PEM → DER.  wc_PemToDer expects (buffer, length, type,
        // derOut, heap, encryptedInfo, keyFormat).
        DerBuffer* der = nullptr;
        int rc = wc_PemToDer(pem.data(), static_cast<long>(n), CERT_TYPE,
                             &der, nullptr, nullptr, nullptr);
        if (rc != 0 || !der || der->length <= 0) {
            if (der) wc_FreeDer(&der);
            return;
        }

        // RFC 8122 / draft-ietf-mmusic-rfc4572-update: the SDP
        // `a=fingerprint` attribute value is the SHA-256 hash of the
        // entire DER-encoded X.509 certificate (including its
        // signature), NOT the SPKI.  Chrome's BoringSSL verifier hashes
        // the cert it receives during the DTLS Certificate flight and
        // compares against the SDP value, so any mismatch — including
        // hashing only the SPKI — triggers fatal alert 46
        // ("certificate_unknown") and the WebRTC PeerConnection
        // transitions to "failed".  See `cert_sha256_hex` above for
        // the full rationale.
        std::string fp_hex = cert_sha256_hex(der->buffer,
                                             static_cast<std::size_t>(der->length));
        if (fp_hex.empty()) {
            wc_FreeDer(&der);
            return;
        }

        // Convert lowercase hex → 32 raw bytes for the Fingerprint struct.
        std::vector<std::uint8_t> raw(32);
        for (std::size_t i = 0; i < 32; ++i) {
            auto v = [](char c) -> int {
                if (c >= '0' && c <= '9') return c - '0';
                if (c >= 'a' && c <= 'f') return c - 'a' + 10;
                if (c >= 'A' && c <= 'F') return c - 'A' + 10;
                return -1;
            };
            int hi = v(fp_hex[static_cast<std::size_t>(2*i)]);
            int lo = v(fp_hex[static_cast<std::size_t>(2*i + 1)]);
            raw[i] = static_cast<std::uint8_t>((hi << 4) | lo);
        }

        // RFC 8122 SDP form: colon-separated UPPER hex.
        std::string hex_colon;
        hex_colon.reserve(32 * 3);
        for (std::size_t i = 0; i < 32; ++i) {
            char buf[4];
            std::snprintf(buf, sizeof(buf), "%02X", raw[i]);
            hex_colon += buf;
            if (i + 1 < 32) hex_colon += ':';
        }

        local_fp_.algorithm = "sha-256";
        local_fp_.bytes    = std::move(raw);
        local_fp_.hex_colon = std::move(hex_colon);
        local_fp_.base64.clear();   // not used; keep base64 legacy empty

        wc_FreeDer(&der);
    }

    bool create_ssl_object() {
        if (!ctx) return false;
        ssl = wolfSSL_new(ctx);
        if (!ssl) {
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: failed to create SSL object");
            return false;
        }

        wolfSSL_set_using_nonblock(ssl, 1);

        // Per-SSL I/O callbacks (vs. CTX-level which would apply to all
        // sessions created from this CTX).  We want a different ctx per
        // session.
        wolfSSL_SetIOReadCtx(ssl, this);
        wolfSSL_SetIOWriteCtx(ssl, this);
        wolfSSL_SSLSetIORecv(ssl, &DtlsSessionWolfSSL::Impl::io_recv);
        wolfSSL_SSLSetIOSend(ssl, &DtlsSessionWolfSSL::Impl::io_send);

        return true;
    }

    void set_peer(const std::string& host, std::uint16_t port) {
        if (peer_set && peer_host == host && peer_port == port) return;
        peer_host = host;
        peer_port = port;
        peer_set  = true;
        std::memset(&peer_addr, 0, sizeof(peer_addr));
        peer_addr.sin_family = AF_INET;
        peer_addr.sin_port   = htons(port);
        inet_pton(AF_INET, host.c_str(), &peer_addr.sin_addr);
        if (ssl) {
            wolfSSL_dtls_set_peer(ssl, &peer_addr, sizeof(peer_addr));
        }
    }

    // -- Handshake pump -----------------------------------------------------

    void flush_send_buf() {
        if (send_buf_.empty()) return;
        nimrtc::dtls::DtlsRecord rec;
        rec.bytes = std::move(send_buf_);
        rec.to.host = peer_host;
        rec.to.port = peer_port;
        outbound_.push_back(std::move(rec));
        ++stats_instance.records_out;
        send_buf_.clear();
    }

    bool pump_handshake() {
        if (!ssl ||
            state == nimrtc::dtls::DtlsState::Connected ||
            state == nimrtc::dtls::DtlsState::Failed) {
            return false;
        }

        // Reentrancy guard.  `take_outbound()` may be called from inside
        // a `pump_handshake()` invocation (e.g. via a transport callback
        // that pulls records synchronously); without this flag we'd
        // recurse until the stack blows up.  See the `pumping_`
        // declaration in the Impl struct.
        if (pumping_) return false;
        pumping_ = true;
        struct PumpGuard {
            bool& flag;
            ~PumpGuard() { flag = false; }
        } guard{pumping_};

        if (state == nimrtc::dtls::DtlsState::Initial) {
            state = nimrtc::dtls::DtlsState::HelloSent;
            handshake_start_ = std::chrono::steady_clock::now();
            nimrtc::core::log::Logger::instance().info(
                std::string("wolfSSL handshake start (role=") +
                (config.role == DtlsRole::Server ? "Server" : "Client") + ")");
            nimrtc::dtls::diag::trace(std::string("HS_START role=") +
                (config.role == DtlsRole::Server ? "Server" : "Client"));
        }

        int rc = (config.role == DtlsRole::Server)
                   ? wolfSSL_accept(ssl)
                   : wolfSSL_connect(ssl);

        if (rc == WOLFSSL_SUCCESS) {
            // SPKI fingerprint pinning must run BEFORE we export SRTP keys
            // or mark the session Connected — a pinned-mismatch must take
            // the session to Failed, never silently to Connected.
            if (!verify_peer_spki()) {
                nimrtc::core::log::Logger::instance().error(
                    "wolfSSL: peer SPKI fingerprint mismatch — handshake rejected");
                state = nimrtc::dtls::DtlsState::Failed;
                ++stats_instance.errors;
                flush_send_buf();
                return true;
            }
            on_handshake_complete();
            flush_send_buf();
            return true;
        }

        int err = wolfSSL_get_error(ssl, rc);
        if (err == WOLFSSL_ERROR_WANT_READ ||
            err == WOLFSSL_ERROR_WANT_WRITE) {
            flush_send_buf();
            return false;
        }

        // If the peer sent a fatal alert, the TLS alert description
        // (level + description bytes) is preserved in
        // `wolfSSL_get_alert_history()` (wolfSSL keeps the most recent
        // alert from either side).  Log it explicitly so we can
        // distinguish chrome-side rejections (unsupported_certificate,
        // illegal_parameter, certificate_required, etc.) from generic
        // handshake_failure without having to attach a packet capture.
        std::string alert_detail;
        if (ssl) {
            WOLFSSL_ALERT_HISTORY hist{};
            if (wolfSSL_get_alert_history(ssl, &hist) == WOLFSSL_SUCCESS) {
                if (hist.last_rx.level != alert_none &&
                    hist.last_rx.code  != invalid_alert) {
                    const char* lname = wolfSSL_alert_type_string(
                        static_cast<int>(hist.last_rx.level));
                    const char* dname = wolfSSL_alert_desc_string(
                        hist.last_rx.code);
                    alert_detail = std::string(" [peer-alert level=") +
                                   (lname ? lname : "?") +
                                   " description=" +
                                   std::to_string(hist.last_rx.code) +
                                   " (" + (dname ? dname : "?") + ")]";
                }
            }
        }
        const char* reason = wolfSSL_ERR_reason_error_string(static_cast<unsigned long>(err));
        nimrtc::core::log::Logger::instance().error(
            std::string("wolfSSL handshake failed: ") +
            std::to_string(err) + " " + (reason ? reason : "") + alert_detail);
        nimrtc::dtls::diag::trace(std::string("HS_FAIL err=") +
            std::to_string(err) + " " + (reason ? reason : "") + alert_detail);
        state = nimrtc::dtls::DtlsState::Failed;
        ++stats_instance.errors;
        flush_send_buf();
        return true;
    }

    // Post-handshake SPKI fingerprint pinning (WebRTC SDP `a=fingerprint`).
    //
    // We deliberately do this AFTER wolfSSL_accept/connect returns success.
    // The setup_context() callback uses WOLFSSL_VERIFY_PEER +
    // dummy_verify_callback so that wolfSSL walks the cert chain and
    // populates ssl->peerCert (which is gated by KEEP_PEER_CERT and only
    // runs when `args->fatal == 0` — i.e. when our callback overrides
    // any chain-validity errors).  We are the trust anchor for
    // self-signed WebRTC peer certs; the actual MITM check is here.
    bool verify_peer_spki() {
        if (!ssl) return false;
        if (!expected_peer_fp_set_) {
            // WebRTC mandates SDP "a=fingerprint" for every peer, so a
            // legitimate caller MUST have called set_peer_fingerprint()
            // before the handshake completed.  However, the
            // *handshake itself* does not require a pin to succeed —
            // Chrome's behaviour is fail-open here (it logs an error
            // to the JS console but the SRTP session still comes up),
            // and forcing fail-closed breaks every demo path where the
            // application forgets to wire the fingerprint early enough.
            //
            // We therefore LOG (warn) here and let the handshake complete;
            // the caller can later call set_peer_fingerprint() and use
            // dtls.stats().errors to detect that no verification ran.
            // Production deployments MUST set a fingerprint — silence
            // this warning before shipping.
            nimrtc::core::log::Logger::instance().warn(
                "wolfSSL: no peer SPKI fingerprint was configured before "
                "handshake — accepting WITHOUT MITM protection. "
                "Call set_peer_fingerprint() from the SDP \"a=fingerprint\" "
                "attribute in production code.");
            ++stats_instance.errors;  // surface in metrics even though we proceed
            return true;  // fail-open
        }
        if (expected_peer_fp_.size() != 32) {
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: expected_peer_fp_ has invalid length " +
                std::to_string(expected_peer_fp_.size()) +
                " (expected 32 bytes raw)");
            return false;
        }

        WOLFSSL_X509* peer = wolfSSL_get_peer_certificate(ssl);
        if (!peer) {
            // peerCert wasn't populated despite the handshake succeeding
            // — happens if wolfSSL was built without KEEP_PEER_CERT or
            // without OPENSSL_EXTRA.  Check
            // src/third_party/wolfssl/CMakeLists.txt — both must be on
            // (KEEP_PEER_CERT is force-injected via target_compile_definitions;
            // OPENSSL_EXTRA is set via WOLFSSL_OPENSSLEXTRA="yes").  We
            // don't have a useful peer cert to pin against, so we
            // fail-closed rather than silently accepting an unknown peer.
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: wolfSSL_get_peer_certificate returned NULL — "
                "wolfSSL build missing KEEP_PEER_CERT or OPENSSL_EXTRA");
            return false;
        }
        // Hold ownership until we return; free at scope exit.
        struct PeerHolder {
            WOLFSSL_X509* p;
            ~PeerHolder() { if (p) wolfSSL_X509_free(p); }
        } holder{peer};

        int der_len = 0;
        const unsigned char* der_buf = wolfSSL_X509_get_der(peer, &der_len);
        if (der_len <= 0 || !der_buf) {
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: failed to extract peer cert DER bytes");
            return false;
        }
        // RFC 8122 / draft-ietf-mmusic-rfc4572-update: SDP `a=fingerprint`
        // is SHA-256 of the entire DER-encoded X.509 certificate, NOT
        // the SPKI.  Hash the full peer's DER cert and compare against
        // the SDP-pinned value.  See `cert_sha256_hex` for the rationale.
        std::string fp_hex = cert_sha256_hex(
            reinterpret_cast<const std::uint8_t*>(der_buf),
            static_cast<std::size_t>(der_len));
        if (fp_hex.empty()) {
            nimrtc::core::log::Logger::instance().error(
                "wolfSSL: cert hash failed for peer cert");
            return false;
        }

        // Decode the hex string back to raw bytes for constant-time
        // comparison against `expected_peer_fp_`.
        std::vector<std::uint8_t> got(32, 0);
        for (std::size_t i = 0; i < 32; ++i) {
            auto hex = [](char c) -> int {
                if (c >= '0' && c <= '9') return c - '0';
                if (c >= 'a' && c <= 'f') return c - 'a' + 10;
                if (c >= 'A' && c <= 'F') return c - 'A' + 10;
                return -1;
            };
            int hi = hex(fp_hex[2*i]);
            int lo = hex(fp_hex[2*i + 1]);
            if (hi < 0 || lo < 0) {
                nimrtc::core::log::Logger::instance().error(
                    "wolfSSL: SPKI hex decoding failed");
                return false;
            }
            got[i] = static_cast<std::uint8_t>((hi << 4) | lo);
        }

        // Constant-time comparison (avoids timing oracles on fingerprint).
        std::uint8_t diff = 0;
        for (std::size_t i = 0; i < 32; ++i) {
            diff |= static_cast<std::uint8_t>(got[i] ^ expected_peer_fp_[i]);
        }
        if (diff != 0) {
            nimrtc::core::log::Logger::instance().error(
                std::string("wolfSSL: peer cert SHA-256 mismatch — got ") +
                fp_hex);
            return false;
        }

        nimrtc::core::log::Logger::instance().info(
            std::string("wolfSSL: peer cert SHA-256 match (") + fp_hex + ")");
        return true;
    }

    void on_handshake_complete() {
        state = nimrtc::dtls::DtlsState::Connected;

        auto elapsed = std::chrono::steady_clock::now() - handshake_start_;
        stats_instance.handshake_ms =
            static_cast<std::uint64_t>(
                std::chrono::duration_cast<std::chrono::milliseconds>(
                    elapsed).count());

        nimrtc::core::log::Logger::instance().info(
            "wolfSSL DTLS handshake complete in " +
            std::to_string(stats_instance.handshake_ms) + " ms");

        const char* cipher = wolfSSL_get_cipher(ssl);
        if (cipher) {
            nimrtc::core::log::Logger::instance().info(
                std::string("wolfSSL cipher: ") + cipher);
        }

        // Record the negotiated SRTP profile on the trace so Wireshark /
        // verify_dtls_handshake.py can confirm Chrome's
        // a=crypto:inline / SDP SRTP profile matches what wolfSSL ended
        // up using to derive keying material.
        nimrtc::dtls::diag::trace(std::string("HS_COMPLETE ms=") +
            std::to_string(stats_instance.handshake_ms) +
            " cipher=" + (cipher ? cipher : "?"));

        // Emit a NSS-format CLIENT_RANDOM line so Wireshark / tshark can
        // decrypt the DTLS stream.  This bypasses wolfSSL's
        // `keyLogCb` for server-side handshakes — wolfSSL 6.x only
        // fires that callback from SendClientKeyExchange (the client),
        // never from DoClientKeyExchange (the server), so the
        // CTX-level callback we registered at setup_context() never
        // sees the secret when NimRTC is the server.  Reading the
        // secret straight out of `ssl->arrays` after accept() returns
        // WOLFSSL_SUCCESS is the documented escape hatch (BoringSSL's
        // debug builds do the same thing) and is safe because by this
        // point the handshake has authenticated the peer.
        if (ssl && nimrtc::dtls::diag::keylog_path()) {
            nimrtc::dtls::diag::write_keylog_line(
                ssl->arrays->clientRandom,
                ssl->arrays->masterSecret);
        }

        export_srtp_keys();
    }

    void export_srtp_keys() {
        if (!ssl || !srtp_keys_) return;

        // wolfSSL requires a TWO-STEP call (per examples and source):
        //   1) Pass NULL buffer to query required length
        //      (returns LENGTH_ONLY_E; olen is set to the required size).
        //   2) Pass real buffer + length to fetch the keying material.
        // Note: wolfSSL return values are NOT WOLFSSL_SUCCESS for these —
        // LENGTH_ONLY_E (~250) on first call, 0 (or WOLFSSL_SUCCESS) on
        // second call.
        std::size_t olen = 0;
        int rc = wolfSSL_export_dtls_srtp_keying_material(ssl, nullptr, &olen);
        if (olen == 0) {
            // No DTLS-SRTP extension negotiated → can't get keying material.
            nimrtc::core::log::Logger::instance().error(
                std::string("wolfSSL: SRTP length-query returned 0 bytes (rc=") +
                std::to_string(rc) + ") — DTLS-SRTP extension not negotiated");
            srtp_keys_.reset();
            return;
        }
        nimrtc::core::log::Logger::instance().info(
            std::string("wolfSSL: SRTP needs ") + std::to_string(olen) + " bytes");

        std::vector<std::uint8_t> km(olen);
        rc = wolfSSL_export_dtls_srtp_keying_material(ssl, km.data(), &olen);
        if (rc != 0 && rc != WOLFSSL_SUCCESS) {
            nimrtc::core::log::Logger::instance().error(
                std::string("wolfSSL: SRTP export failed rc=") +
                std::to_string(rc) + " olen=" + std::to_string(olen));
            srtp_keys_.reset();
            return;
        }

        auto& keys = *srtp_keys_;
        // RFC 5764 §4.2 keying material layout (60 bytes total):
        //  [client master key  : 16 bytes]
        //  [server master key  : 16 bytes]
        //  [client master salt : 14 bytes]
        //  [server master salt : 14 bytes]
        std::memcpy(keys.client_master_key.data(),  km.data() +  0, 16);
        std::memcpy(keys.server_master_key.data(), km.data() + 16, 16);
        std::memcpy(keys.client_master_salt.data(),km.data() + 32, 14);
        std::memcpy(keys.server_master_salt.data(),km.data() + 46, 14);

        nimrtc::core::log::Logger::instance().info(
            "wolfSSL: SRTP keying material exported (" +
            std::to_string(olen) + " bytes)");
    }

    void teardown() {
        if (ssl) {
            wolfSSL_shutdown(ssl);
            wolfSSL_free(ssl);
            ssl = nullptr;
        }
        if (ctx) {
            wolfSSL_CTX_free(ctx);
            ctx = nullptr;
        }
        state = nimrtc::dtls::DtlsState::Closed;
    }
};

// ---------------------------------------------------------------------------
// DtlsSessionWolfSSL public API
// ---------------------------------------------------------------------------

DtlsSessionWolfSSL::DtlsSessionWolfSSL(Config cfg)
    : impl_(std::make_unique<Impl>()) {
    impl_->config = cfg;
    impl_->state  = nimrtc::dtls::DtlsState::Initial;
    impl_->srtp_keys_.emplace();
}

DtlsSessionWolfSSL::~DtlsSessionWolfSSL() = default;

DtlsSessionWolfSSL::DtlsSessionWolfSSL(DtlsSessionWolfSSL&&) noexcept = default;
DtlsSessionWolfSSL& DtlsSessionWolfSSL::operator=(
    DtlsSessionWolfSSL&&) noexcept = default;

nimrtc::core::Result<void> DtlsSessionWolfSSL::open() noexcept {
    if (impl_->open_called) return nimrtc::core::Result<void>::make_ok();
    impl_->open_called = true;

    static bool g_init = false;
    if (!g_init) {
        if (wolfSSL_Init() != WOLFSSL_SUCCESS) {
            nimrtc::core::log::Logger::instance().error("wolfSSL_Init failed");
            ++impl_->stats_instance.errors;
            return nimrtc::core::Result<void>::fail(
                nimrtc::core::ErrorCode::InternalError,
                "wolfSSL_Init failed");
        }
        g_init = true;
    }

    if (!impl_->setup_context()) {
        ++impl_->stats_instance.errors;
        return nimrtc::core::Result<void>::fail(
            nimrtc::core::ErrorCode::InternalError,
            "wolfSSL_CTX setup failed");
    }

    if (!impl_->create_ssl_object()) {
        ++impl_->stats_instance.errors;
        return nimrtc::core::Result<void>::fail(
            nimrtc::core::ErrorCode::InternalError,
            "wolfSSL_new failed");
    }

    nimrtc::core::log::Logger::instance().info(
        std::string("DtlsSessionWolfSSL::open — fingerprint=") +
        impl_->local_fp_.hex_colon);

    return nimrtc::core::Result<void>::make_ok();
}

void DtlsSessionWolfSSL::close() noexcept {
    impl_->teardown();
}

std::size_t DtlsSessionWolfSSL::feed_inbound(
        std::span<const std::uint8_t> bytes,
        const nimrtc::dtls::DtlsAddr& from) noexcept {
    if (bytes.empty()) return 0;
    ++impl_->stats_instance.records_in;

    // Per-record hex dump so the trace shows EXACTLY what Chrome sent on
    // every invocation.  Unlike the io_recv callback (which wolfSSL drains
    // internally and may skip if recv_buf_ is empty), this fires on every
    // datagram that the ICE/UDP layer delivers, regardless of whether
    // wolfSSL immediately processes it.
    {
        std::string dump;
        dump.reserve(bytes.size() * 3);
        for (std::size_t i = 0; i < bytes.size() && i < 64; ++i) {
            char b[4];
            std::snprintf(b, sizeof(b), "%02x", bytes[i]);
            dump += b;
            if (i + 1 < bytes.size() && i + 1 < 64) dump += ' ';
        }
        if (bytes.size() > 64) dump += " ...";
        nimrtc::dtls::diag::trace(
            "feed_inbound " + std::to_string(bytes.size()) + "B hex=" + dump);
    }

    // Also log the local DTLS fingerprint on the very first packet so
    // we can confirm what SDP `a=fingerprint` advertises and what
    // Chrome's verifier will hash the cert against.
    //
    // The "fingerprint" itself is the SHA-256 of the entire DER-encoded
    // X.509 certificate (RFC 8122 / draft-ietf-mmusic-rfc4572-update),
    // so both forms below describe the SAME value — hex colon-separated
    // for the SDP, base64 for any consumer that prefers b64.
    //
    // NOTE: Chrome's --ignore-certificate-errors-spki-list expects the
    // SPKI hash, not the cert hash, and only affects HTTPS — it has
    // never been relevant for the WebRTC DTLS path here.
    {
        static bool logged_fp = false;
        const auto& fp = this->local_fingerprint();
        if (!logged_fp && !fp.bytes.empty()) {
            logged_fp = true;
            // RFC 8122 colon-hex form (for SDP a=fingerprint).
            char hex[130] = "LOCAL_FP_HEX=";
            for (std::size_t i = 0; i < fp.bytes.size(); ++i) {
                char b[4];
                std::snprintf(b, sizeof(b), "%02X", fp.bytes[i]);
                std::strncat(hex, b, 2);
                if (i + 1 < fp.bytes.size()) std::strncat(hex, ":", 1);
            }
            nimrtc::dtls::diag::trace(hex);
            // base64 form (handy for grep/jq against external scripts).
            static const char kB64[] =
                "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
            std::string b64;
            std::size_t i = 0;
            while (i + 3 <= fp.bytes.size()) {
                std::uint32_t v = (static_cast<std::uint32_t>(fp.bytes[i]) << 16)
                                | (static_cast<std::uint32_t>(fp.bytes[i+1]) << 8)
                                |  static_cast<std::uint32_t>(fp.bytes[i+2]);
                b64 += kB64[(v >> 18) & 0x3f];
                b64 += kB64[(v >> 12) & 0x3f];
                b64 += kB64[(v >>  6) & 0x3f];
                b64 += kB64[ v        & 0x3f];
                i += 3;
            }
            if (i < fp.bytes.size()) {
                std::uint32_t v = static_cast<std::uint32_t>(fp.bytes[i]) << 16;
                if (i + 1 < fp.bytes.size()) v |= static_cast<std::uint32_t>(fp.bytes[i+1]) << 8;
                b64 += kB64[(v >> 18) & 0x3f];
                b64 += kB64[(v >> 12) & 0x3f];
                if (i + 1 < fp.bytes.size()) b64 += kB64[(v >> 6) & 0x3f];
            }
            nimrtc::dtls::diag::trace(std::string("LOCAL_FP_B64=") + b64);
        }
    }

    if (!from.host.empty() && from.port != 0) {
        impl_->set_peer(from.host, from.port);
    }

    auto old = impl_->recv_buf_.size();
    impl_->recv_buf_.resize(old + bytes.size());
    std::memcpy(impl_->recv_buf_.data() + old, bytes.data(), bytes.size());

    impl_->pump_handshake();

    return bytes.size();
}

std::vector<nimrtc::dtls::DtlsRecord>
DtlsSessionWolfSSL::take_outbound() noexcept {
    auto recs = std::move(impl_->outbound_);
    impl_->outbound_.clear();

    // Re-pump the handshake: wolfSSL may have more bytes to send after
    // we drained the previous batch.  We use `pump_handshake()` instead
    // of `wolfSSL_dtls_got_timeout()` here because the I/O callbacks
    // (`io_recv`/`io_send`) have a full picture only when paired with
    // an explicit accept()/connect() call.
    //
    // Reentrancy: `pump_handshake()` may itself call `flush_send_buf()`
    // recursively, but the `Impl::pumping_` flag (set in `tick()` /
    // `pump_handshake()`) prevents unbounded recursion.
    if (impl_->ssl &&
        impl_->state != nimrtc::dtls::DtlsState::Connected &&
        impl_->state != nimrtc::dtls::DtlsState::Failed &&
        impl_->state != nimrtc::dtls::DtlsState::Closed) {
        impl_->pump_handshake();
        auto more = std::move(impl_->outbound_);
        impl_->outbound_.clear();
        for (auto& r : more) recs.push_back(std::move(r));
    }
    return recs;
}

void DtlsSessionWolfSSL::tick() noexcept {
    if (!impl_->ssl ||
        impl_->state == nimrtc::dtls::DtlsState::Connected ||
        impl_->state == nimrtc::dtls::DtlsState::Failed ||
        impl_->state == nimrtc::dtls::DtlsState::Closed) {
        return;
    }

    // Advance the wolfSSL internal retransmit timer.  When the timer
    // fires, wolfSSL re-emits the last flight of handshake records into
    // our `io_send` callback (appended to `send_buf_`).  We then drain
    // them into `outbound_` so the transport layer can ship them.
    //
    // RFC 6347 §4.2.4: the initial retransmit timer is 1 s with
    // exponential backoff up to 60 s.  Without this pump, a stalled
    // handshake (e.g. lost HelloVerifyRequest) hangs forever.
    //
    // wolfSSL_dtls_got_timeout() returns:
    //   0  — timer not yet fired, nothing to do
    //   1  — timer fired; wolfSSL re-emitted the last flight (caller
    //        should call accept()/connect() again to drive the state
    //        machine forward)
    //  <0  — wolfSSL error (treat as timer-not-fired)
    const int ret = wolfSSL_dtls_got_timeout(impl_->ssl);
    if (ret <= 0) return;  // no retransmit pending, or wolfSSL errored
    ++impl_->stats_instance.retransmits;
    // Flush whatever wolfSSL re-emitted into send_buf_ as part of the
    // retransmit into outbound_.  We do NOT pump the handshake here:
    //
    //   * `take_outbound()` (called from `engine::drain_dtls()` right
    //     after this tick) already re-pumps via `pump_handshake()` so
    //     any newly-produced bytes from the retransmit get appended to
    //     the returned vector.
    //
    //   * Pumping here as well would mean `wolfSSL_accept()` is invoked
    //     TWICE per retransmit tick — once from this `pump_handshake()`
    //     and once from `take_outbound()`'s.  wolfSSL's internal
    //     retransmit bookkeeping doesn't have a chance to be reset
    //     between the two, so the same flight gets re-sent twice.  In
    //     Chrome interop we have observed this manifest as 3+ copies of
    //     the ServerHello/Certificate/ServerKeyExchange/ServerHelloDone
    //     flight being emitted between ICE-connected and the arrival of
    //     the peer's ClientKeyExchange.  Chrome treats the duplicated
    //     flights as a protocol violation and aborts the handshake —
    //     see `nimrtc_chrome.trace` for the `seq=0..3, seq=4..7,
    //     seq=8..11` triple-emission pattern that this used to produce.
    //
    // Flushing alone is enough to surface the retransmitted bytes; the
    // caller drains them via `take_outbound()`.
    impl_->flush_send_buf();
}

nimrtc::dtls::DtlsState DtlsSessionWolfSSL::state() const noexcept {
    return impl_->state;
}

bool DtlsSessionWolfSSL::is_connected() const noexcept {
    return impl_->state == nimrtc::dtls::DtlsState::Connected &&
           impl_->ssl &&
           wolfSSL_is_init_finished(impl_->ssl);
}

const char* DtlsSessionWolfSSL::state_name(
    nimrtc::dtls::DtlsState s) noexcept {
    using nimrtc::dtls::DtlsState;
    switch (s) {
        case DtlsState::Closed:              return "Closed";
        case DtlsState::Initial:             return "Initial";
        case DtlsState::HelloVerify:         return "HelloVerify";
        case DtlsState::HelloSent:           return "HelloSent";
        case DtlsState::HelloReceived:       return "HelloReceived";
        case DtlsState::CertificateReceived: return "CertificateReceived";
        case DtlsState::KeyExchange:         return "KeyExchange";
        case DtlsState::ChangeCipherSpec:    return "ChangeCipherSpec";
        case DtlsState::Finished:            return "Finished";
        case DtlsState::Connected:           return "Connected";
        case DtlsState::Failed:              return "Failed";
    }
    return "Unknown";
}

const nimrtc::dtls::Fingerprint&
DtlsSessionWolfSSL::local_fingerprint() const noexcept {
    return impl_->local_fp_;
}

void DtlsSessionWolfSSL::set_peer_fingerprint(
        std::string algo,
        std::vector<std::uint8_t> value) noexcept {
    // Stored as raw 32-byte SHA-256 digest.  Only "sha-256" is recognised
    // for 1.0 (matches WebRTC's SDP `a=fingerprint` attribute).  An empty
    // value clears the pin; the next handshake will fail loudly via
    // verify_peer_callback since no CA chain is configured.
    if (algo != "sha-256") {
        nimrtc::core::log::Logger::instance().warn(
            std::string("DtlsSessionWolfSSL: unsupported fingerprint algo '") +
            algo + "' (expected sha-256) — clearing pin");
        impl_->expected_peer_fp_.clear();
        impl_->expected_peer_fp_set_ = false;
        return;
    }
    if (value.size() != 32) {
        nimrtc::core::log::Logger::instance().warn(
            std::string("DtlsSessionWolfSSL: peer fingerprint must be 32 bytes, got ") +
            std::to_string(value.size()) + " — clearing pin");
        impl_->expected_peer_fp_.clear();
        impl_->expected_peer_fp_set_ = false;
        return;
    }
    impl_->expected_peer_fp_ = std::move(value);
    impl_->expected_peer_fp_set_ = true;
    nimrtc::core::log::Logger::instance().info(
        "DtlsSessionWolfSSL: peer fingerprint pin set");
}

void DtlsSessionWolfSSL::set_role(nimrtc::dtls::DtlsRole r) noexcept {
    using nimrtc::dtls::DtlsState;
    if (impl_->state != DtlsState::Closed &&
        impl_->state != DtlsState::Initial) {
        nimrtc::core::log::Logger::instance().warn(
            "DtlsSessionWolfSSL: role change after handshake ignored");
        return;
    }
    impl_->config.role = r;
    nimrtc::core::log::Logger::instance().info(
        std::string("DtlsSessionWolfSSL: role=") +
        (r == DtlsRole::Server ? "Server" : "Client"));
}

std::optional<nimrtc::dtls::SrtpKeyingMaterial>
DtlsSessionWolfSSL::srtp_keying_material() const noexcept {
    if (impl_->state != nimrtc::dtls::DtlsState::Connected) return std::nullopt;
    return impl_->srtp_keys_;
}

DtlsSessionWolfSSL::Stats DtlsSessionWolfSSL::stats() const noexcept {
    return impl_->stats_instance;
}

} // namespace nimrtc::dtls

// Undefine Windows headers' "New" macro (preprocessor poison for any
// subsequent translation unit that includes this file via PCH).
#ifdef New
#undef New
#endif
